spring:
  application:
    name: forohub
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/forohub}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8081

# JWT Configuration
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key-for-forohub-application-2024}
      issuer: ForoHub API

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging
logging:
  level:
    com.forohub: INFO
    org.springframework.security: DEBUG
