# Configuración para producción en Render
spring:
  # Base de datos PostgreSQL - CONFIGURACIÓN EXTREMA PARA EVITAR BUG HIKARI
  datasource:
    # NO usar url directa - separar componentes manualmente
    username: forohubbd_user
    password: fiiN7nC7FbSYX0xIsMQ8a5PpjtwF57R5
    driver-class-name: org.postgresql.Driver
    # URL sin parámetros SSL
    url: jdbc:postgresql://dpg-d2in02buibrs73a14dl0-a.oregon-postgres.render.com:5432/forohubbd
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      # Configuración SSL separada
      data-source-properties:
        sslmode: require
        stringtype: unspecified
        ApplicationName: ForoHub
        prepareThreshold: 0

  # EXCLUSIÓN CRÍTICA: Flyway causa dependencia circular
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

  # JPA/Hibernate - CONFIGURACIÓN SIMPLE PARA POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
    defer-datasource-initialization: true
    open-in-view: false

# Configuración del servidor
server:
  port: ${PORT:10000}
  # Configuración adicional para Render
  tomcat:
    threads:
      max: 10
      min-spare: 2

# Configuración management para health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  # Configuración optimizada para Render
  tomcat:
    connection-timeout: 20000
    keep-alive-timeout: 20000
    max-connections: 100
    threads:
      max: 20
      min-spare: 5
  error:
    include-message: always
    include-binding-errors: always

# JWT
api:
  security:
    token:
      secret: ${JWT_SECRET}

# Logging para producción
logging:
  level:
    com.forohub: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
