spring:
  profiles:
    active: debug
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: ${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
  h2:
    console:
      enabled: true

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

api:
  security:
    token:
      secret: ${JWT_SECRET:secret-key-for-testing-only}

logging:
  level:
    com.forohub: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: INFO
