# Configuraci贸n para producci贸n en Render
spring:
  # Base de datos PostgreSQL (Render)
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Flyway deshabilitado temporalmente
  flyway:
    enabled: false

# Configuraci贸n del servidor
server:
  port: ${PORT:10000}
  error:
    include-message: always
    include-binding-errors: always

# JWT
api:
  security:
    token:
      secret: ${JWT_SECRET:mi-clave-secreta-super-segura-para-jwt-forohub-2024}

# Logging para producci贸n
logging:
  level:
    com.forohub: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
