# Configuración para producción en Render
spring:
  # Base de datos PostgreSQL (Render)
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    # Configuración de Hikari para PostgreSQL
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
  
  # Flyway deshabilitado temporalmente
  flyway:
    enabled: false

# Configuración del servidor
server:
  port: ${PORT:10000}
  error:
    include-message: always
    include-binding-errors: always

# JWT
api:
  security:
    token:
      secret: ${JWT_SECRET:mi-clave-secreta-super-segura-para-jwt-forohub-2024}

# Logging para producción
logging:
  level:
    com.forohub: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
